import axios from "axios";
import Head from "next/head";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";
import {
  Box,
  Button,
  Table,
  TableCaption,
  Tbody,
  Td,
  Tfoot,
  Th,
  Thead,
  Tr,
} from "@chakra-ui/react";
import NewsCards from "../components/NewsCards/NewsCards";
import CreateNewsModal from "../components/CreateNewsModal/CreateNewsModal";
import { axiosGet } from "../helpers/axiosCalls";
import { format } from "date-fns";
import { DeleteIcon, EditIcon } from "@chakra-ui/icons";

export default function Home() {
  const [news, setNews] = useState();
  const [tags, setTags] = useState();

  const getNews = async () => {
    await axiosGet("/news", setNews);
  };

  const getTags = async () => {
    await axios.get("http://localhost:4000/tags/").then((response) => {
      setTags(response.data.data);
    });
  };
  useEffect(() => {
    getNews();
    getTags();
  }, []);

  return (
    <div className={styles.container}>
      <CreateNewsModal tags={tags} />
      <Head>
        <title>News Api</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Table variant="simple">
        <Thead>
          <Tr>
            <Th>ID</Th>
            <Th>Headline</Th>
            <Th>Date</Th>
            <Th isNumeric></Th>
          </Tr>
        </Thead>
        <Tbody>
          {news?.map((news) => {
            return (
              <Tr key={news.id}>
                <Td>{news.id}</Td>
                <Td>{news.headline}</Td>
                <Td>{format(new Date(news.date), "dd-MM-yyyy")}</Td>
                <Td isNumeric>
                  <Button marginRight={2} onClick>
                    <EditIcon />
                  </Button>
                  <Button>
                    <DeleteIcon />
                  </Button>
                </Td>
              </Tr>
            );
          })}
        </Tbody>
      </Table>
    </div>
  );
}
