import axios from "axios";
import Head from "next/head";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";
import { Box } from "@chakra-ui/react";
import NewsCards from "../components/NewsCards/NewsCards";
import CreateNewsModal from "../components/CreateNewsModal/CreateNewsModal";

export default function Home() {
  const [data, setData] = useState();

  const getNews = async () => {
    await axios.get("http://localhost:4000/news/").then((response) => {
      setData(response.data.data);
    });
  };
  useEffect(() => {
    getNews();
  }, []);

  return (
    <div className={styles.container}>
      <CreateNewsModal />
      <Head>
        <title>News Api</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box w={300}>
        {data?.map((news) => {
          return <NewsCards {...news}></NewsCards>;
        })}
      </Box>
    </div>
  );
}
